pin "beautiful_photons/index", to: "beautiful_photons/index.js"
pin "beautiful_photons/focal_point_controller", to: "beautiful_photons/focal_point_controller.js"
pin "beautiful_photons/reorder_controller", to: "beautiful_photons/reorder_controller.js"
pin "beautiful_photons/crop_editor_controller", to: "beautiful_photons/crop_editor_controller.js"
pin "beautiful_photons/bulk_select_controller", to: "beautiful_photons/bulk_select_controller.js"
